### ISSUE TITLE
Smart Mobility description

### ISSUE THREAD

**Issue by edblayney** [LouisvilleMetro/OPI2-Home#14]
# Smart Mobility 

The transportation sector is in a period of transformation. Technology and data are changing the way that people and goods are moving in our community, and we expect this transformation to continue for decades. To help our organization embrace these changes and great the greatest benefit from them, we work with transportation organizations in Louisville Metro Government and our community to help them make plans for emerging techonologies, build data tools for their daily work and continuous improvement, and build their workforce for these disruptive innovations.

Some of our projects include:
* Developing a comprehensive Intelligent Transportation System modernization plan
* Creating an Autonomous Vehicle Playbook
* Creating tools using crowdsourced data to evaluate traffic congestion problem areas and traffic improvement projects
* Developing a transportation focused data warehouse for all Metro related transportation data

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/OPI2-Home#3
