### ISSUE TITLE
Smart City Description

### ISSUE THREAD

**Issue by edblayney** [LouisvilleMetro/OPI2-Home#15]
# Smart City Strategy

In the next 20 years, Louisville Metro, as a community and government organization, will be transformed by technology. We will have fiber optic cable to the home in every neighborhood; sensors that will collect information on everything from odors to noise pollution; autonomous vehicles on our streets; and on and on. Technology will drive change in our physical, economic, and digital environment. We must prepare for our technology-enabled world. 

Our Smart City strategy aims to enhance the abilities of public service employees and citizens by empowering them to solve public problems through the use of existing and emerging technologies. It does this by starting with understanding the challenges our departments and community face and then incorporating technologies that can help solve the problems rather than thinking that technology alone will fix them. This problem-driven approach looks at the full-spectrum of technologies needed to enhance a service from platforms and infrastructure needed to support technologies, to the technologies themselves, and the data-management necessary to empower government employees and citizens to make data-driven decisions for our community.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/OPI2-Home#2
