### ISSUE TITLE
Innovation Advisory Council description

### ISSUE THREAD

**Issue by edblayney** [LouisvilleMetro/OPI2-Home#16]
# Innovation Advisory Council

The Innovation Advisory Council is a diverse collection of residents with a variety of backgrounds, appointed by executive order, to advise the mayor on the city’s innovation efforts. They are responsible for overseeing the operations of the LouieLab and providing feedback on the Office of Civic Innovation’s strategy. 

The council meets monthly to discuss current or potential community issues related to emerging technologies, providing specific feedback on current projects and plans. Twice a year, the council hosts open meetings to engage the public on the city's work and to gather input and feedback on innovation related topics. 

To learn more about the council's work, email Ed Blayney, ed.blayney@louisvilleky.gov

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/OPI2-Home#1
