### ISSUE TITLE
Some broken links and such

### ISSUE THREAD

**Issue by schnuerle** [LouisvilleMetro/OPI2-Home#18]
Contact email and email link is ipoall@ not opiall@

Mobility animation is 5MB so takes too long to load. Static image might be better. https://opi.lsvll.io/innovation/smart-mobility/

Learn More link on Mobility page goes to 404. https://opi.lsvll.io/innovation/smart-mobility/

Events link does not work: https://opi.lsvll.io/events/

Innovation's Go to Project Site opens a new tab - and Learn More on projects site opens a new tab.  This means jumping between the sites open multiple tabs.  I think they should just stay in same tab all the time.  This happens on the Learn More links in the body content too.
​
What does Follow this Project do?  You get an email any time the page is updated?

**Comment by schnuerle** [comment]
For the home page image we've got to give attribution: https://www.flickr.com/photos/helloeveryone123/25177610695/

**Comment by mgottholsen** [comment]
Added issues to https://github.com/louisvillemetro-innovation/OPI2-Home/issuesm, closing & archiving this repo.
